# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Mkdocs Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.in ]; then pip install -r requirements.in; fi
    - name: Publish with mkdocs
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Actions"
        git pull
        mkdocs gh-deploy
